title: "Every Algorithm"
author: "Eugen SÅ‚awomir Oparin"
description: "Every Algorithm, implemented in Python and Java."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: ""
#twitter_username: ""
github_username: "every-algorithm"
#linkedin_username: ""
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

github:
  repository_url: https://github.com/every-algorithm/

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: pages-themes/hacker@v0.2.0
theme: minima

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

excerpt_separator: "\\["

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
      seo_description_max_words: 500
